# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import stt_pb2 as stt__pb2
import stt_response_pb2 as stt__response__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in stt_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class STTStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FileRecognize = channel.unary_unary(
                '/mts.ai.audiogram.stt.v3.STT/FileRecognize',
                request_serializer=stt__pb2.FileRecognizeRequest.SerializeToString,
                response_deserializer=stt__response__pb2.FileRecognizeResponse.FromString,
                _registered_method=True)
        self.Recognize = channel.stream_stream(
                '/mts.ai.audiogram.stt.v3.STT/Recognize',
                request_serializer=stt__pb2.RecognizeRequest.SerializeToString,
                response_deserializer=stt__response__pb2.RecognizeResponse.FromString,
                _registered_method=True)
        self.GetModelsInfo = channel.unary_unary(
                '/mts.ai.audiogram.stt.v3.STT/GetModelsInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stt__pb2.ModelsInfo.FromString,
                _registered_method=True)


class STTServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FileRecognize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recognize(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelsInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_STTServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FileRecognize': grpc.unary_unary_rpc_method_handler(
                    servicer.FileRecognize,
                    request_deserializer=stt__pb2.FileRecognizeRequest.FromString,
                    response_serializer=stt__response__pb2.FileRecognizeResponse.SerializeToString,
            ),
            'Recognize': grpc.stream_stream_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=stt__pb2.RecognizeRequest.FromString,
                    response_serializer=stt__response__pb2.RecognizeResponse.SerializeToString,
            ),
            'GetModelsInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelsInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stt__pb2.ModelsInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mts.ai.audiogram.stt.v3.STT', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mts.ai.audiogram.stt.v3.STT', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class STT(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FileRecognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mts.ai.audiogram.stt.v3.STT/FileRecognize',
            stt__pb2.FileRecognizeRequest.SerializeToString,
            stt__response__pb2.FileRecognizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recognize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/mts.ai.audiogram.stt.v3.STT/Recognize',
            stt__pb2.RecognizeRequest.SerializeToString,
            stt__response__pb2.RecognizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelsInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mts.ai.audiogram.stt.v3.STT/GetModelsInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stt__pb2.ModelsInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
