"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _AudioEncoding:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AudioEncodingEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AudioEncoding.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ENCODING_UNSPECIFIED: _AudioEncoding.ValueType
    LINEAR_PCM: _AudioEncoding.ValueType
    FLAC: _AudioEncoding.ValueType
    MULAW: _AudioEncoding.ValueType
    ALAW: _AudioEncoding.ValueType

class AudioEncoding(_AudioEncoding, metaclass=_AudioEncodingEnumTypeWrapper):
    ...
ENCODING_UNSPECIFIED: AudioEncoding.ValueType
LINEAR_PCM: AudioEncoding.ValueType
FLAC: AudioEncoding.ValueType
MULAW: AudioEncoding.ValueType
ALAW: AudioEncoding.ValueType
global___AudioEncoding = AudioEncoding

class _AttackType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AttackTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AttackType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    LOGICAL: _AttackType.ValueType
    PHYSICAL: _AttackType.ValueType
    ALL_TYPES: _AttackType.ValueType

class AttackType(_AttackType, metaclass=_AttackTypeEnumTypeWrapper):
    ...
LOGICAL: AttackType.ValueType
PHYSICAL: AttackType.ValueType
ALL_TYPES: AttackType.ValueType
global___AttackType = AttackType

@typing_extensions.final
class FileRecognizeRequest(google.protobuf.message.Message):
    """REQUEST CONFIG BEGIN"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CONFIG_FIELD_NUMBER: builtins.int
    AUDIO_FIELD_NUMBER: builtins.int

    @property
    def config(self) -> global___RecognitionConfig:
        ...
    audio: builtins.bytes

    def __init__(self, *, config: global___RecognitionConfig | None=..., audio: builtins.bytes=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['config', b'config']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['audio', b'audio', 'config', b'config']) -> None:
        ...
global___FileRecognizeRequest = FileRecognizeRequest

@typing_extensions.final
class RecognizeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CONFIG_FIELD_NUMBER: builtins.int
    AUDIO_FIELD_NUMBER: builtins.int

    @property
    def config(self) -> global___StreamRecognitionConfig:
        ...
    audio: builtins.bytes

    def __init__(self, *, config: global___StreamRecognitionConfig | None=..., audio: builtins.bytes=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['audio', b'audio', 'config', b'config', 'streaming_request', b'streaming_request']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['audio', b'audio', 'config', b'config', 'streaming_request', b'streaming_request']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing_extensions.Literal['streaming_request', b'streaming_request']) -> typing_extensions.Literal['config', 'audio'] | None:
        ...
global___RecognizeRequest = RecognizeRequest

@typing_extensions.final
class RecognitionConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _VoiceActivityMarkEventsMode:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _VoiceActivityMarkEventsModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[RecognitionConfig._VoiceActivityMarkEventsMode.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        VA_DISABLE: RecognitionConfig._VoiceActivityMarkEventsMode.ValueType
        VA_ENABLE: RecognitionConfig._VoiceActivityMarkEventsMode.ValueType
        VA_ENABLE_ASYNC: RecognitionConfig._VoiceActivityMarkEventsMode.ValueType

    class VoiceActivityMarkEventsMode(_VoiceActivityMarkEventsMode, metaclass=_VoiceActivityMarkEventsModeEnumTypeWrapper):
        ...
    VA_DISABLE: RecognitionConfig.VoiceActivityMarkEventsMode.ValueType
    VA_ENABLE: RecognitionConfig.VoiceActivityMarkEventsMode.ValueType
    VA_ENABLE_ASYNC: RecognitionConfig.VoiceActivityMarkEventsMode.ValueType
    ENCODING_FIELD_NUMBER: builtins.int
    SAMPLE_RATE_HERTZ_FIELD_NUMBER: builtins.int
    LANGUAGE_CODE_FIELD_NUMBER: builtins.int
    AUDIO_CHANNEL_COUNT_FIELD_NUMBER: builtins.int
    SPLIT_BY_CHANNEL_FIELD_NUMBER: builtins.int
    MODEL_FIELD_NUMBER: builtins.int
    ENABLE_WORD_TIME_OFFSETS_FIELD_NUMBER: builtins.int
    VA_CONFIG_FIELD_NUMBER: builtins.int
    VA_RESPONSE_MODE_FIELD_NUMBER: builtins.int
    GENDERAGE_CONFIG_FIELD_NUMBER: builtins.int
    ANTISPOOFING_CONFIG_FIELD_NUMBER: builtins.int
    CONTEXT_DICTIONARY_FIELD_NUMBER: builtins.int
    PUNCTUATION_CONFIG_FIELD_NUMBER: builtins.int
    DENORMALIZATION_CONFIG_FIELD_NUMBER: builtins.int
    SPEAKER_LABELING_CONFIG_FIELD_NUMBER: builtins.int
    encoding: global___AudioEncoding.ValueType
    sample_rate_hertz: builtins.int
    language_code: builtins.str
    audio_channel_count: builtins.int
    split_by_channel: builtins.bool
    model: builtins.str
    enable_word_time_offsets: builtins.bool

    @property
    def va_config(self) -> global___VoiceActivityConfig:
        ...
    va_response_mode: global___RecognitionConfig.VoiceActivityMarkEventsMode.ValueType

    @property
    def genderage_config(self) -> global___GenderAgeEmotionConfig:
        ...

    @property
    def antispoofing_config(self) -> global___AntiSpoofingConfig:
        ...

    @property
    def context_dictionary(self) -> global___ContextDictionaryConfig:
        ...

    @property
    def punctuation_config(self) -> global___PunctuationConfig:
        ...

    @property
    def denormalization_config(self) -> global___DenormalizationConfig:
        ...

    @property
    def speaker_labeling_config(self) -> global___SpeakerLabelingConfig:
        ...

    def __init__(self, *, encoding: global___AudioEncoding.ValueType=..., sample_rate_hertz: builtins.int=..., language_code: builtins.str=..., audio_channel_count: builtins.int=..., split_by_channel: builtins.bool=..., model: builtins.str=..., enable_word_time_offsets: builtins.bool=..., va_config: global___VoiceActivityConfig | None=..., va_response_mode: global___RecognitionConfig.VoiceActivityMarkEventsMode.ValueType=..., genderage_config: global___GenderAgeEmotionConfig | None=..., antispoofing_config: global___AntiSpoofingConfig | None=..., context_dictionary: global___ContextDictionaryConfig | None=..., punctuation_config: global___PunctuationConfig | None=..., denormalization_config: global___DenormalizationConfig | None=..., speaker_labeling_config: global___SpeakerLabelingConfig | None=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['antispoofing_config', b'antispoofing_config', 'context_dictionary', b'context_dictionary', 'denormalization_config', b'denormalization_config', 'genderage_config', b'genderage_config', 'punctuation_config', b'punctuation_config', 'speaker_labeling_config', b'speaker_labeling_config', 'va_config', b'va_config']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['antispoofing_config', b'antispoofing_config', 'audio_channel_count', b'audio_channel_count', 'context_dictionary', b'context_dictionary', 'denormalization_config', b'denormalization_config', 'enable_word_time_offsets', b'enable_word_time_offsets', 'encoding', b'encoding', 'genderage_config', b'genderage_config', 'language_code', b'language_code', 'model', b'model', 'punctuation_config', b'punctuation_config', 'sample_rate_hertz', b'sample_rate_hertz', 'speaker_labeling_config', b'speaker_labeling_config', 'split_by_channel', b'split_by_channel', 'va_config', b'va_config', 'va_response_mode', b'va_response_mode']) -> None:
        ...
global___RecognitionConfig = RecognitionConfig

@typing_extensions.final
class StreamRecognitionConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CONFIG_FIELD_NUMBER: builtins.int
    SINGLE_UTTERANCE_FIELD_NUMBER: builtins.int
    INTERIM_RESULTS_FIELD_NUMBER: builtins.int

    @property
    def config(self) -> global___RecognitionConfig:
        ...
    single_utterance: builtins.bool
    interim_results: builtins.bool

    def __init__(self, *, config: global___RecognitionConfig | None=..., single_utterance: builtins.bool=..., interim_results: builtins.bool=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['config', b'config']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['config', b'config', 'interim_results', b'interim_results', 'single_utterance', b'single_utterance']) -> None:
        ...
global___StreamRecognitionConfig = StreamRecognitionConfig

@typing_extensions.final
class VoiceActivityConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _VoiceActivityDetectionAlgorithmUsage:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _VoiceActivityDetectionAlgorithmUsageEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[VoiceActivityConfig._VoiceActivityDetectionAlgorithmUsage.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        USE_VAD: VoiceActivityConfig._VoiceActivityDetectionAlgorithmUsage.ValueType
        DO_NOT_PERFORM_VOICE_ACTIVITY: VoiceActivityConfig._VoiceActivityDetectionAlgorithmUsage.ValueType
        USE_DEP: VoiceActivityConfig._VoiceActivityDetectionAlgorithmUsage.ValueType

    class VoiceActivityDetectionAlgorithmUsage(_VoiceActivityDetectionAlgorithmUsage, metaclass=_VoiceActivityDetectionAlgorithmUsageEnumTypeWrapper):
        ...
    USE_VAD: VoiceActivityConfig.VoiceActivityDetectionAlgorithmUsage.ValueType
    DO_NOT_PERFORM_VOICE_ACTIVITY: VoiceActivityConfig.VoiceActivityDetectionAlgorithmUsage.ValueType
    USE_DEP: VoiceActivityConfig.VoiceActivityDetectionAlgorithmUsage.ValueType
    USAGE_FIELD_NUMBER: builtins.int
    VAD_OPTIONS_FIELD_NUMBER: builtins.int
    DEP_OPTIONS_FIELD_NUMBER: builtins.int
    usage: global___VoiceActivityConfig.VoiceActivityDetectionAlgorithmUsage.ValueType

    @property
    def vad_options(self) -> global___VADOptions:
        ...

    @property
    def dep_options(self) -> global___DEPOptions:
        ...

    def __init__(self, *, usage: global___VoiceActivityConfig.VoiceActivityDetectionAlgorithmUsage.ValueType=..., vad_options: global___VADOptions | None=..., dep_options: global___DEPOptions | None=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['algo_options', b'algo_options', 'dep_options', b'dep_options', 'vad_options', b'vad_options']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['algo_options', b'algo_options', 'dep_options', b'dep_options', 'usage', b'usage', 'vad_options', b'vad_options']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing_extensions.Literal['algo_options', b'algo_options']) -> typing_extensions.Literal['vad_options', 'dep_options'] | None:
        ...
global___VoiceActivityConfig = VoiceActivityConfig

@typing_extensions.final
class VADOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _VoiceActivityDetectionMode:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _VoiceActivityDetectionModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[VADOptions._VoiceActivityDetectionMode.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        VAD_MODE_DEFAULT: VADOptions._VoiceActivityDetectionMode.ValueType
        SPLIT_BY_PAUSES: VADOptions._VoiceActivityDetectionMode.ValueType
        ONLY_SPEECH: VADOptions._VoiceActivityDetectionMode.ValueType

    class VoiceActivityDetectionMode(_VoiceActivityDetectionMode, metaclass=_VoiceActivityDetectionModeEnumTypeWrapper):
        ...
    VAD_MODE_DEFAULT: VADOptions.VoiceActivityDetectionMode.ValueType
    SPLIT_BY_PAUSES: VADOptions.VoiceActivityDetectionMode.ValueType
    ONLY_SPEECH: VADOptions.VoiceActivityDetectionMode.ValueType
    THRESHOLD_FIELD_NUMBER: builtins.int
    SPEECH_PAD_MS_FIELD_NUMBER: builtins.int
    MIN_SILENCE_MS_FIELD_NUMBER: builtins.int
    MIN_SPEECH_MS_FIELD_NUMBER: builtins.int
    MODE_FIELD_NUMBER: builtins.int
    threshold: builtins.float
    speech_pad_ms: builtins.int
    min_silence_ms: builtins.int
    min_speech_ms: builtins.int
    mode: global___VADOptions.VoiceActivityDetectionMode.ValueType

    def __init__(self, *, threshold: builtins.float=..., speech_pad_ms: builtins.int=..., min_silence_ms: builtins.int=..., min_speech_ms: builtins.int=..., mode: global___VADOptions.VoiceActivityDetectionMode.ValueType=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['min_silence_ms', b'min_silence_ms', 'min_speech_ms', b'min_speech_ms', 'mode', b'mode', 'speech_pad_ms', b'speech_pad_ms', 'threshold', b'threshold']) -> None:
        ...
global___VADOptions = VADOptions

@typing_extensions.final
class DEPOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SMOOTHED_WINDOW_THRESHOLD_FIELD_NUMBER: builtins.int
    SMOOTHED_WINDOW_MS_FIELD_NUMBER: builtins.int
    smoothed_window_threshold: builtins.float
    smoothed_window_ms: builtins.int

    def __init__(self, *, smoothed_window_threshold: builtins.float=..., smoothed_window_ms: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['smoothed_window_ms', b'smoothed_window_ms', 'smoothed_window_threshold', b'smoothed_window_threshold']) -> None:
        ...
global___DEPOptions = DEPOptions

@typing_extensions.final
class GenderAgeEmotionConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ENABLE_FIELD_NUMBER: builtins.int
    enable: builtins.bool

    def __init__(self, *, enable: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['enable', b'enable']) -> None:
        ...
global___GenderAgeEmotionConfig = GenderAgeEmotionConfig

@typing_extensions.final
class AntiSpoofingConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TYPE_FIELD_NUMBER: builtins.int
    FAR_FIELD_NUMBER: builtins.int
    FRR_FIELD_NUMBER: builtins.int
    MAX_DURATION_FOR_ANALYSIS_MS_FIELD_NUMBER: builtins.int
    ENABLE_FIELD_NUMBER: builtins.int
    type: global___AttackType.ValueType
    FAR: builtins.float
    'Допустимый процент принятия ботов за людей'
    FRR: builtins.float
    'Допустимый процент отклонения людей (принятия их за ботов)'
    max_duration_for_analysis_ms: builtins.int
    enable: builtins.bool

    def __init__(self, *, type: global___AttackType.ValueType=..., FAR: builtins.float=..., FRR: builtins.float=..., max_duration_for_analysis_ms: builtins.int=..., enable: builtins.bool=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['FAR', b'FAR', 'FRR', b'FRR', 'false_rate_type', b'false_rate_type']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['FAR', b'FAR', 'FRR', b'FRR', 'enable', b'enable', 'false_rate_type', b'false_rate_type', 'max_duration_for_analysis_ms', b'max_duration_for_analysis_ms', 'type', b'type']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing_extensions.Literal['false_rate_type', b'false_rate_type']) -> typing_extensions.Literal['FAR', 'FRR'] | None:
        ...
global___AntiSpoofingConfig = AntiSpoofingConfig

@typing_extensions.final
class ContextDictionaryConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DICTIONARY_NAME_FIELD_NUMBER: builtins.int
    WEIGHT_FIELD_NUMBER: builtins.int
    dictionary_name: builtins.str
    weight: builtins.float

    def __init__(self, *, dictionary_name: builtins.str=..., weight: builtins.float=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['dictionary_name', b'dictionary_name', 'weight', b'weight']) -> None:
        ...
global___ContextDictionaryConfig = ContextDictionaryConfig

@typing_extensions.final
class PunctuationConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ENABLE_FIELD_NUMBER: builtins.int
    enable: builtins.bool

    def __init__(self, *, enable: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['enable', b'enable']) -> None:
        ...
global___PunctuationConfig = PunctuationConfig

@typing_extensions.final
class DenormalizationConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ENABLE_FIELD_NUMBER: builtins.int
    enable: builtins.bool

    def __init__(self, *, enable: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['enable', b'enable']) -> None:
        ...
global___DenormalizationConfig = DenormalizationConfig

@typing_extensions.final
class SpeakerLabelingConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ENABLE_FIELD_NUMBER: builtins.int
    MAX_SPEAKERS_FIELD_NUMBER: builtins.int
    NUM_SPEAKERS_FIELD_NUMBER: builtins.int
    enable: builtins.bool
    max_speakers: builtins.int
    num_speakers: builtins.int

    def __init__(self, *, enable: builtins.bool=..., max_speakers: builtins.int=..., num_speakers: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['max_speakers', b'max_speakers', 'num_speakers', b'num_speakers', 'speakers', b'speakers']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['enable', b'enable', 'max_speakers', b'max_speakers', 'num_speakers', b'num_speakers', 'speakers', b'speakers']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing_extensions.Literal['speakers', b'speakers']) -> typing_extensions.Literal['max_speakers', 'num_speakers'] | None:
        ...
global___SpeakerLabelingConfig = SpeakerLabelingConfig

@typing_extensions.final
class FileRecognizeResponse(google.protobuf.message.Message):
    """RESPONSE BEGIN"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESPONSE_FIELD_NUMBER: builtins.int

    @property
    def response(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RecognizeResponse]:
        ...

    def __init__(self, *, response: collections.abc.Iterable[global___RecognizeResponse] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['response', b'response']) -> None:
        ...
global___FileRecognizeResponse = FileRecognizeResponse

@typing_extensions.final
class RecognizeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HYPOTHESIS_FIELD_NUMBER: builtins.int
    IS_FINAL_FIELD_NUMBER: builtins.int
    CHANNEL_FIELD_NUMBER: builtins.int
    VA_MARKS_FIELD_NUMBER: builtins.int
    GENDERAGE_FIELD_NUMBER: builtins.int
    SPOOFING_RESULT_FIELD_NUMBER: builtins.int
    SPEAKER_INFO_FIELD_NUMBER: builtins.int

    @property
    def hypothesis(self) -> global___SpeechRecognitionHypothesis:
        ...
    is_final: builtins.bool
    channel: builtins.int

    @property
    def va_marks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___VoiceActivityMark]:
        ...

    @property
    def genderage(self) -> global___SpeakerGenderAgePrediction:
        ...

    @property
    def spoofing_result(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SpoofingResult]:
        ...

    @property
    def speaker_info(self) -> global___SpeakerInfo:
        ...

    def __init__(self, *, hypothesis: global___SpeechRecognitionHypothesis | None=..., is_final: builtins.bool=..., channel: builtins.int=..., va_marks: collections.abc.Iterable[global___VoiceActivityMark] | None=..., genderage: global___SpeakerGenderAgePrediction | None=..., spoofing_result: collections.abc.Iterable[global___SpoofingResult] | None=..., speaker_info: global___SpeakerInfo | None=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['genderage', b'genderage', 'hypothesis', b'hypothesis', 'speaker_info', b'speaker_info']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['channel', b'channel', 'genderage', b'genderage', 'hypothesis', b'hypothesis', 'is_final', b'is_final', 'speaker_info', b'speaker_info', 'spoofing_result', b'spoofing_result', 'va_marks', b'va_marks']) -> None:
        ...
global___RecognizeResponse = RecognizeResponse

@typing_extensions.final
class SpeechRecognitionHypothesis(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class WordInfo(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        START_TIME_MS_FIELD_NUMBER: builtins.int
        END_TIME_MS_FIELD_NUMBER: builtins.int
        WORD_FIELD_NUMBER: builtins.int
        CONFIDENCE_FIELD_NUMBER: builtins.int
        start_time_ms: builtins.int
        end_time_ms: builtins.int
        word: builtins.str
        confidence: builtins.float

        def __init__(self, *, start_time_ms: builtins.int=..., end_time_ms: builtins.int=..., word: builtins.str=..., confidence: builtins.float=...) -> None:
            ...

        def ClearField(self, field_name: typing_extensions.Literal['confidence', b'confidence', 'end_time_ms', b'end_time_ms', 'start_time_ms', b'start_time_ms', 'word', b'word']) -> None:
            ...
    TRANSCRIPT_FIELD_NUMBER: builtins.int
    NORMALIZED_TRANSCRIPT_FIELD_NUMBER: builtins.int
    CONFIDENCE_FIELD_NUMBER: builtins.int
    START_TIME_MS_FIELD_NUMBER: builtins.int
    END_TIME_MS_FIELD_NUMBER: builtins.int
    WORDS_FIELD_NUMBER: builtins.int
    NORMALIZED_WORDS_FIELD_NUMBER: builtins.int
    transcript: builtins.str
    normalized_transcript: builtins.str
    'all postprocessing'
    confidence: builtins.float
    start_time_ms: builtins.int
    end_time_ms: builtins.int

    @property
    def words(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SpeechRecognitionHypothesis.WordInfo]:
        ...

    @property
    def normalized_words(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SpeechRecognitionHypothesis.WordInfo]:
        ...

    def __init__(self, *, transcript: builtins.str=..., normalized_transcript: builtins.str=..., confidence: builtins.float=..., start_time_ms: builtins.int=..., end_time_ms: builtins.int=..., words: collections.abc.Iterable[global___SpeechRecognitionHypothesis.WordInfo] | None=..., normalized_words: collections.abc.Iterable[global___SpeechRecognitionHypothesis.WordInfo] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['confidence', b'confidence', 'end_time_ms', b'end_time_ms', 'normalized_transcript', b'normalized_transcript', 'normalized_words', b'normalized_words', 'start_time_ms', b'start_time_ms', 'transcript', b'transcript', 'words', b'words']) -> None:
        ...
global___SpeechRecognitionHypothesis = SpeechRecognitionHypothesis

@typing_extensions.final
class VoiceActivityMark(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _VoiceActivityMarkType:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _VoiceActivityMarkTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[VoiceActivityMark._VoiceActivityMarkType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        VA_MARK_NONE: VoiceActivityMark._VoiceActivityMarkType.ValueType
        VA_MARK_BEGIN: VoiceActivityMark._VoiceActivityMarkType.ValueType
        VA_MARK_END: VoiceActivityMark._VoiceActivityMarkType.ValueType

    class VoiceActivityMarkType(_VoiceActivityMarkType, metaclass=_VoiceActivityMarkTypeEnumTypeWrapper):
        ...
    VA_MARK_NONE: VoiceActivityMark.VoiceActivityMarkType.ValueType
    VA_MARK_BEGIN: VoiceActivityMark.VoiceActivityMarkType.ValueType
    VA_MARK_END: VoiceActivityMark.VoiceActivityMarkType.ValueType
    MARK_TYPE_FIELD_NUMBER: builtins.int
    OFFSET_MS_FIELD_NUMBER: builtins.int
    mark_type: global___VoiceActivityMark.VoiceActivityMarkType.ValueType
    offset_ms: builtins.int

    def __init__(self, *, mark_type: global___VoiceActivityMark.VoiceActivityMarkType.ValueType=..., offset_ms: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['mark_type', b'mark_type', 'offset_ms', b'offset_ms']) -> None:
        ...
global___VoiceActivityMark = VoiceActivityMark

@typing_extensions.final
class SpeakerGenderAgePrediction(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _GenderClass:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _GenderClassEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[SpeakerGenderAgePrediction._GenderClass.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        GENDER_UNDEF: SpeakerGenderAgePrediction._GenderClass.ValueType
        GENDER_MALE: SpeakerGenderAgePrediction._GenderClass.ValueType
        GENDER_FEMALE: SpeakerGenderAgePrediction._GenderClass.ValueType

    class GenderClass(_GenderClass, metaclass=_GenderClassEnumTypeWrapper):
        ...
    GENDER_UNDEF: SpeakerGenderAgePrediction.GenderClass.ValueType
    GENDER_MALE: SpeakerGenderAgePrediction.GenderClass.ValueType
    GENDER_FEMALE: SpeakerGenderAgePrediction.GenderClass.ValueType

    class _AgeClass:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _AgeClassEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[SpeakerGenderAgePrediction._AgeClass.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        AGE_UNDEF: SpeakerGenderAgePrediction._AgeClass.ValueType
        AGE_ADULT: SpeakerGenderAgePrediction._AgeClass.ValueType
        AGE_CHILD: SpeakerGenderAgePrediction._AgeClass.ValueType

    class AgeClass(_AgeClass, metaclass=_AgeClassEnumTypeWrapper):
        ...
    AGE_UNDEF: SpeakerGenderAgePrediction.AgeClass.ValueType
    AGE_ADULT: SpeakerGenderAgePrediction.AgeClass.ValueType
    AGE_CHILD: SpeakerGenderAgePrediction.AgeClass.ValueType

    @typing_extensions.final
    class EmotionsRecognition(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        POSITIVE_FIELD_NUMBER: builtins.int
        NEUTRAL_FIELD_NUMBER: builtins.int
        NEGATIVE_ANGRY_FIELD_NUMBER: builtins.int
        NEGATIVE_SAD_FIELD_NUMBER: builtins.int
        positive: builtins.float
        neutral: builtins.float
        negative_angry: builtins.float
        negative_sad: builtins.float

        def __init__(self, *, positive: builtins.float=..., neutral: builtins.float=..., negative_angry: builtins.float=..., negative_sad: builtins.float=...) -> None:
            ...

        def ClearField(self, field_name: typing_extensions.Literal['negative_angry', b'negative_angry', 'negative_sad', b'negative_sad', 'neutral', b'neutral', 'positive', b'positive']) -> None:
            ...
    GENDER_FIELD_NUMBER: builtins.int
    AGE_FIELD_NUMBER: builtins.int
    EMOTION_FIELD_NUMBER: builtins.int
    gender: global___SpeakerGenderAgePrediction.GenderClass.ValueType
    'пол спикера'
    age: global___SpeakerGenderAgePrediction.AgeClass.ValueType
    'возраст спикера'

    @property
    def emotion(self) -> global___SpeakerGenderAgePrediction.EmotionsRecognition:
        """эмоция спикера"""

    def __init__(self, *, gender: global___SpeakerGenderAgePrediction.GenderClass.ValueType=..., age: global___SpeakerGenderAgePrediction.AgeClass.ValueType=..., emotion: global___SpeakerGenderAgePrediction.EmotionsRecognition | None=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['emotion', b'emotion']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['age', b'age', 'emotion', b'emotion', 'gender', b'gender']) -> None:
        ...
global___SpeakerGenderAgePrediction = SpeakerGenderAgePrediction

@typing_extensions.final
class SpoofingResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _AttackResult:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _AttackResultEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[SpoofingResult._AttackResult.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        ATTACK_DETECTED: SpoofingResult._AttackResult.ValueType
        GENUINE: SpoofingResult._AttackResult.ValueType

    class AttackResult(_AttackResult, metaclass=_AttackResultEnumTypeWrapper):
        ...
    ATTACK_DETECTED: SpoofingResult.AttackResult.ValueType
    GENUINE: SpoofingResult.AttackResult.ValueType
    TYPE_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    CONFIDENCE_FIELD_NUMBER: builtins.int
    START_TIME_MS_FIELD_NUMBER: builtins.int
    END_TIME_MS_FIELD_NUMBER: builtins.int
    type: global___AttackType.ValueType
    result: global___SpoofingResult.AttackResult.ValueType
    confidence: builtins.float
    start_time_ms: builtins.int
    end_time_ms: builtins.int

    def __init__(self, *, type: global___AttackType.ValueType=..., result: global___SpoofingResult.AttackResult.ValueType=..., confidence: builtins.float=..., start_time_ms: builtins.int=..., end_time_ms: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['confidence', b'confidence', 'end_time_ms', b'end_time_ms', 'result', b'result', 'start_time_ms', b'start_time_ms', 'type', b'type']) -> None:
        ...
global___SpoofingResult = SpoofingResult

@typing_extensions.final
class SpeakerInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SPEAKER_ID_FIELD_NUMBER: builtins.int
    speaker_id: builtins.int

    def __init__(self, *, speaker_id: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['speaker_id', b'speaker_id']) -> None:
        ...
global___SpeakerInfo = SpeakerInfo

@typing_extensions.final
class ModelsInfo(google.protobuf.message.Message):
    """MODELS INFO BEGIN"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODELS_FIELD_NUMBER: builtins.int

    @property
    def models(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ModelInfo]:
        ...

    def __init__(self, *, models: collections.abc.Iterable[global___ModelInfo] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['models', b'models']) -> None:
        ...
global___ModelsInfo = ModelsInfo

@typing_extensions.final
class ModelInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    SAMPLE_RATE_HERTZ_FIELD_NUMBER: builtins.int
    LANGUAGE_CODE_FIELD_NUMBER: builtins.int
    DICTIONARY_NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    sample_rate_hertz: builtins.int
    language_code: builtins.str

    @property
    def dictionary_name(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        ...

    def __init__(self, *, name: builtins.str=..., sample_rate_hertz: builtins.int=..., language_code: builtins.str=..., dictionary_name: collections.abc.Iterable[builtins.str] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['dictionary_name', b'dictionary_name', 'language_code', b'language_code', 'name', b'name', 'sample_rate_hertz', b'sample_rate_hertz']) -> None:
        ...
global___ModelInfo = ModelInfo