"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import collections.abc
import google.protobuf.empty_pb2
import grpc
import grpc.aio
from . import tts_pb2
import typing
_T = typing.TypeVar('_T')

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta):
    ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):
    ...

class TTSStub:

    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None:
        ...
    StreamingSynthesize: grpc.UnaryStreamMultiCallable[tts_pb2.SynthesizeSpeechRequest, tts_pb2.StreamingSynthesizeSpeechResponse]
    Synthesize: grpc.UnaryUnaryMultiCallable[tts_pb2.SynthesizeSpeechRequest, tts_pb2.SynthesizeSpeechResponse]
    GetModelsInfo: grpc.UnaryUnaryMultiCallable[google.protobuf.empty_pb2.Empty, tts_pb2.ModelsInfo]

class TTSAsyncStub:
    StreamingSynthesize: grpc.aio.UnaryStreamMultiCallable[tts_pb2.SynthesizeSpeechRequest, tts_pb2.StreamingSynthesizeSpeechResponse]
    Synthesize: grpc.aio.UnaryUnaryMultiCallable[tts_pb2.SynthesizeSpeechRequest, tts_pb2.SynthesizeSpeechResponse]
    GetModelsInfo: grpc.aio.UnaryUnaryMultiCallable[google.protobuf.empty_pb2.Empty, tts_pb2.ModelsInfo]

class TTSServicer(metaclass=abc.ABCMeta):

    @abc.abstractmethod
    def StreamingSynthesize(self, request: tts_pb2.SynthesizeSpeechRequest, context: _ServicerContext) -> typing.Union[collections.abc.Iterator[tts_pb2.StreamingSynthesizeSpeechResponse], collections.abc.AsyncIterator[tts_pb2.StreamingSynthesizeSpeechResponse]]:
        ...

    @abc.abstractmethod
    def Synthesize(self, request: tts_pb2.SynthesizeSpeechRequest, context: _ServicerContext) -> typing.Union[tts_pb2.SynthesizeSpeechResponse, collections.abc.Awaitable[tts_pb2.SynthesizeSpeechResponse]]:
        ...

    @abc.abstractmethod
    def GetModelsInfo(self, request: google.protobuf.empty_pb2.Empty, context: _ServicerContext) -> typing.Union[tts_pb2.ModelsInfo, collections.abc.Awaitable[tts_pb2.ModelsInfo]]:
        ...

def add_TTSServicer_to_server(servicer: TTSServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None:
    ...