# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voice_cloning.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'voice_cloning.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import stt_pb2 as stt__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13voice_cloning.proto\x12!mts.ai.audiogram.voice_cloning.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\tstt.proto\"\x9d\x01\n\x08TaskInfo\x12\x10\n\x08voice_id\x18\x01 \x01(\t\x12\x42\n\x06status\x18\x02 \x01(\x0e\x32\x32.mts.ai.audiogram.voice_cloning.v1.TaskInfo.Status\";\n\x06Status\x12\r\n\tUNDEFINED\x10\x00\x12\x0c\n\x08\x43REATING\x10\x01\x12\t\n\x05READY\x10\x02\x12\t\n\x05\x45RROR\x10\x03\"\x7f\n\x0b\x41udioFormat\x12\x38\n\x08\x65ncoding\x18\x01 \x01(\x0e\x32&.mts.ai.audiogram.stt.v3.AudioEncoding\x12\x19\n\x11sample_rate_hertz\x18\x02 \x01(\r\x12\x1b\n\x13\x61udio_channel_count\x18\x03 \x01(\r\"i\n\x11\x43loneVoiceRequest\x12\x44\n\x0c\x61udio_format\x18\x01 \x01(\x0b\x32..mts.ai.audiogram.voice_cloning.v1.AudioFormat\x12\x0e\n\x06signal\x18\x02 \x01(\x0c\"\x15\n\x06TaskId\x12\x0b\n\x03val\x18\x01 \x01(\t\"&\n\x12\x44\x65leteVoiceRequest\x12\x10\n\x08voice_id\x18\x01 \x01(\t2\xc2\x02\n\x0cVoiceCloning\x12m\n\nCloneVoice\x12\x34.mts.ai.audiogram.voice_cloning.v1.CloneVoiceRequest\x1a).mts.ai.audiogram.voice_cloning.v1.TaskId\x12\x65\n\x0bGetTaskInfo\x12).mts.ai.audiogram.voice_cloning.v1.TaskId\x1a+.mts.ai.audiogram.voice_cloning.v1.TaskInfo\x12\\\n\x0b\x44\x65leteVoice\x12\x35.mts.ai.audiogram.voice_cloning.v1.DeleteVoiceRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_cloning_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKINFO']._serialized_start=99
  _globals['_TASKINFO']._serialized_end=256
  _globals['_TASKINFO_STATUS']._serialized_start=197
  _globals['_TASKINFO_STATUS']._serialized_end=256
  _globals['_AUDIOFORMAT']._serialized_start=258
  _globals['_AUDIOFORMAT']._serialized_end=385
  _globals['_CLONEVOICEREQUEST']._serialized_start=387
  _globals['_CLONEVOICEREQUEST']._serialized_end=492
  _globals['_TASKID']._serialized_start=494
  _globals['_TASKID']._serialized_end=515
  _globals['_DELETEVOICEREQUEST']._serialized_start=517
  _globals['_DELETEVOICEREQUEST']._serialized_end=555
  _globals['_VOICECLONING']._serialized_start=558
  _globals['_VOICECLONING']._serialized_end=880
# @@protoc_insertion_point(module_scope)
