# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import voice_cloning_pb2 as voice__cloning__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in voice_cloning_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoiceCloningStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CloneVoice = channel.unary_unary(
                '/mts.ai.audiogram.voice_cloning.v1.VoiceCloning/CloneVoice',
                request_serializer=voice__cloning__pb2.CloneVoiceRequest.SerializeToString,
                response_deserializer=voice__cloning__pb2.TaskId.FromString,
                _registered_method=True)
        self.GetTaskInfo = channel.unary_unary(
                '/mts.ai.audiogram.voice_cloning.v1.VoiceCloning/GetTaskInfo',
                request_serializer=voice__cloning__pb2.TaskId.SerializeToString,
                response_deserializer=voice__cloning__pb2.TaskInfo.FromString,
                _registered_method=True)
        self.DeleteVoice = channel.unary_unary(
                '/mts.ai.audiogram.voice_cloning.v1.VoiceCloning/DeleteVoice',
                request_serializer=voice__cloning__pb2.DeleteVoiceRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class VoiceCloningServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CloneVoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceCloningServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CloneVoice': grpc.unary_unary_rpc_method_handler(
                    servicer.CloneVoice,
                    request_deserializer=voice__cloning__pb2.CloneVoiceRequest.FromString,
                    response_serializer=voice__cloning__pb2.TaskId.SerializeToString,
            ),
            'GetTaskInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskInfo,
                    request_deserializer=voice__cloning__pb2.TaskId.FromString,
                    response_serializer=voice__cloning__pb2.TaskInfo.SerializeToString,
            ),
            'DeleteVoice': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVoice,
                    request_deserializer=voice__cloning__pb2.DeleteVoiceRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mts.ai.audiogram.voice_cloning.v1.VoiceCloning', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mts.ai.audiogram.voice_cloning.v1.VoiceCloning', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceCloning(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CloneVoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mts.ai.audiogram.voice_cloning.v1.VoiceCloning/CloneVoice',
            voice__cloning__pb2.CloneVoiceRequest.SerializeToString,
            voice__cloning__pb2.TaskId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mts.ai.audiogram.voice_cloning.v1.VoiceCloning/GetTaskInfo',
            voice__cloning__pb2.TaskId.SerializeToString,
            voice__cloning__pb2.TaskInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mts.ai.audiogram.voice_cloning.v1.VoiceCloning/DeleteVoice',
            voice__cloning__pb2.DeleteVoiceRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
